import {createCipheriv,createDecipheriv,createHash,createHmac,randomBytes,timingSafeEqual} from "node:crypto";
import {adminQuery} from "@/lib/db/pool";
import {InputError} from "@/lib/operations-api";

function key(){const raw=process.env.WHATSAPP_TOKEN_KEY;if(!raw)throw new Error("Configure WHATSAPP_TOKEN_KEY.");return createHash("sha256").update(raw).digest();}
export function encryptWhatsAppToken(value:string){const iv=randomBytes(12);const cipher=createCipheriv("aes-256-gcm",key(),iv);const ciphertext=Buffer.concat([cipher.update(value,"utf8"),cipher.final()]);return `${iv.toString("base64url")}.${cipher.getAuthTag().toString("base64url")}.${ciphertext.toString("base64url")}`;}
export function decryptWhatsAppToken(value:string){const [iv,tag,data]=value.split(".");if(!iv||!tag||!data)throw Error("Credencial WhatsApp inválida.");const decipher=createDecipheriv("aes-256-gcm",key(),Buffer.from(iv,"base64url"));decipher.setAuthTag(Buffer.from(tag,"base64url"));return Buffer.concat([decipher.update(Buffer.from(data,"base64url")),decipher.final()]).toString("utf8");}
export function verifyWhatsAppSignature(raw:Buffer,header:string|null){const secret=process.env.WHATSAPP_APP_SECRET;if(!secret||!header?.startsWith("sha256="))return false;const actual=Buffer.from(header.slice(7),"hex");const digest=createHmac("sha256",secret).update(raw).digest();return actual.length===digest.length&&timingSafeEqual(actual,digest);}
export async function whatsAppGraph(phoneNumberId:string,token:string,body:unknown){const version=process.env.WHATSAPP_GRAPH_VERSION||"v25.0";const response=await fetch(`https://graph.facebook.com/${version}/${encodeURIComponent(phoneNumberId)}/messages`,{method:"POST",headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json"},body:JSON.stringify(body),signal:AbortSignal.timeout(15000)});const data=await response.json().catch(()=>({}));if(!response.ok)throw new InputError(typeof data?.error?.message==="string"?data.error.message:"WhatsApp recusou a mensagem.");return data;}
export async function workspaceWhatsApp(workspaceId:string){const row=(await adminQuery("SELECT * FROM whatsapp_connections WHERE workspace_id=$1 AND enabled",[workspaceId])).rows[0];if(!row)throw new InputError("Configure o WhatsApp da empresa antes de enviar mensagens.");return {...row,token:decryptWhatsAppToken(row.token_ciphertext)};}
