"use client";
import {useState} from "react";
import {Button} from "@/components/ui/button";
import {normalizeMappedRows,importFields} from "@/lib/crm-import";
const labels={full_name:"Nome",email:"E-mail",phone:"Telefone com código do país",company:"Empresa (leads)"};
type Preview={id:string;total:number;duplicates:number;newRecords:number};
export function ImportPanel(){
 const [entity,setEntity]=useState("leads"),[headers,setHeaders]=useState<string[]>([]),[rows,setRows]=useState<string[][]>([]),[mapping,setMapping]=useState<Record<string,number>>({}),[preview,setPreview]=useState<Preview|null>(null),[mode,setMode]=useState("skip"),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 const checked=normalizeMappedRows(rows,mapping);const invalid=checked.filter(r=>r.error);
 async function json(action:unknown){const response=await fetch("/api/crm/import",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(action)});const data=await response.json();if(!response.ok)throw Error(data.error);return data;}
 return <section className="space-y-5 rounded-xl border bg-white p-5"><div><h2 className="text-xl font-semibold">Importar contatos e leads</h2><p className="mt-2 text-sm text-muted-foreground">CSV UTF-8 ou Excel (.xlsx), até 2 MB e 1.000 registros. A primeira linha contém os títulos. No Excel, usamos a primeira aba. Nenhum registro é gravado antes da confirmação.</p></div>
 <label className="block text-sm">Importar para<select disabled={busy} className="ml-3 rounded border p-2" value={entity} onChange={e=>{setEntity(e.target.value);setPreview(null);}}><option value="leads">Leads</option><option value="contacts">Contatos</option></select></label>
 <label className="block text-sm">Arquivo<input className="mt-2 block w-full rounded border p-3" disabled={busy} type="file" accept=".csv,.xlsx" onChange={async e=>{const file=e.target.files?.[0];if(!file)return;setBusy(true);setMessage("");setPreview(null);setRows([]);try{if(file.size>2*1024*1024)throw Error("Limite de 2 MB.");const type=file.name.toLowerCase().endsWith(".xlsx")?"xlsx":"csv";const response=await fetch("/api/crm/import/file?type="+type,{method:"POST",body:file});const data=await response.json();if(!response.ok)throw Error(data.error);setHeaders(data.headers);setRows(data.rows);const next:Record<string,number>={};for(const field of importFields)next[field]=data.headers.findIndex((h:string)=>({full_name:["nome","name","full_name"],email:["email","e-mail"],phone:["telefone","phone","whatsapp"],company:["empresa","company"]}[field]).includes(h.trim().toLowerCase()));setMapping(next);}catch(error){setMessage(error instanceof Error?error.message:"Falha na leitura.");}finally{setBusy(false);}}}/></label>
 {rows.length>0 && <><div className="grid gap-3 sm:grid-cols-2">{importFields.map(field=><label key={field} className="text-sm">{labels[field]}<select disabled={busy} className="mt-1 block w-full rounded border p-2" value={mapping[field]??-1} onChange={e=>{setMapping({...mapping,[field]:Number(e.target.value)});setPreview(null);}}><option value={-1}>Não importar</option>{headers.map((h,i)=><option key={i} value={i}>{i+1}. {h}</option>)}</select></label>)}</div><p className="text-sm">{rows.length} registros · {invalid.length} inválidos. Informe nome e pelo menos e-mail ou telefone para identificar duplicados.</p>
 <div className="max-h-64 overflow-auto rounded border"><table className="w-full text-left text-sm"><thead><tr><th className="p-2">Linha</th><th>Nome</th><th>E-mail</th><th>Validação</th></tr></thead><tbody>{checked.slice(0,30).map(r=><tr key={r.line} className="border-t"><td className="p-2">{r.line}</td><td>{r.data?.full_name}</td><td>{r.data?.email}</td><td>{r.error??"Válido"}</td></tr>)}</tbody></table></div><p className="text-xs text-muted-foreground">Amostra das primeiras 30 linhas. A validação considera o arquivo inteiro.</p>{invalid.length>0 && <details><summary>Ver erros de todas as linhas</summary><ul className="max-h-60 overflow-auto text-sm">{invalid.map(r=><li key={r.line}>Linha {r.line}: {r.error}</li>)}</ul></details>}
 <Button disabled={busy||invalid.length>0} onClick={async()=>{setBusy(true);setMessage("");try{setPreview(await json({action:"preview",entity,rows:checked.map(r=>r.data)}));}catch(e){setMessage(e instanceof Error?e.message:"Falha.");}finally{setBusy(false);}}}>Verificar duplicados</Button></>}
 {preview && <div className="space-y-3 rounded border border-violet-200 bg-violet-50 p-4"><h3 className="font-semibold">Confirme a importação</h3><p>{preview.newRecords} novos · {preview.duplicates} possíveis duplicados</p><label className="block text-sm">Ao encontrar duplicados<select disabled={busy} value={mode} onChange={e=>setMode(e.target.value)} className="mt-1 block w-full rounded border bg-white p-2"><option value="skip">Ignorar, preservando o cadastro atual</option><option value="fill">Preencher apenas campos vazios</option></select></label><p className="text-xs">Comparamos e-mail e telefone normalizados. Conflitos entre vários cadastros e registros arquivados são preservados. Nenhum cadastro é excluído ou mesclado automaticamente.</p><Button disabled={busy} onClick={async()=>{setBusy(true);try{const r=await json({action:"commit",id:preview.id,duplicates:mode});setMessage(`Concluído: ${r.created} criados, ${r.updated} preenchidos, ${r.skipped} ignorados, ${r.conflicts} conflitos preservados.`);setPreview(null);setRows([]);}catch(e){setMessage(e instanceof Error?e.message:"Falha.");}finally{setBusy(false);}}}>Confirmar importação</Button></div>}
 {busy && <p role="status">Processando…</p>}{message && <p role="status" className="rounded bg-muted p-3 text-sm">{message}</p>}</section>;
}
