import {NextResponse} from "next/server";
import {createHash,randomBytes} from "node:crypto";
import {z} from "zod";
import {workspaceAccess} from "@/lib/access";
import {adminQuery,transaction} from "@/lib/db/pool";
import {readJson,uuid} from "@/lib/security";
import {operationError,InputError} from "@/lib/operations-api";
const item=z.object({product_id:uuid.nullable().optional(),description:z.string().trim().min(1).max(300),quantity:z.coerce.number().positive().max(100000),unit_price:z.coerce.number().min(0).max(1e12)});
const input=z.object({deal_id:uuid,valid_until:z.string().date().nullable().optional(),notes:z.string().max(4000).default(""),items:z.array(item).min(1).max(100)});
const hash=(token:string)=>createHash("sha256").update(token).digest("hex");
export async function GET(){try{const {workspace}=await workspaceAccess();const result=await adminQuery(`SELECT p.id,p.deal_id,p.version,p.status,p.valid_until,p.notes,p.total,p.sent_at,p.accepted_at,p.created_at,d.title FROM sales_proposals p JOIN deals d ON d.id=p.deal_id WHERE p.workspace_id=$1 ORDER BY p.created_at DESC LIMIT 200`,[workspace.id]);return NextResponse.json(result.rows);}catch(error){return operationError(error);}}
export async function POST(request:Request){try{const {workspace,user}=await workspaceAccess();const data=input.parse(await readJson(request,100000));const result=await transaction(null,async run=>{const deal=(await run("SELECT id FROM deals WHERE id=$1 AND workspace_id=$2",[data.deal_id,workspace.id])).rows[0];if(!deal)throw new InputError("Negócio não encontrado.");const version=Number((await run("SELECT coalesce(max(version),0)+1 AS version FROM sales_proposals WHERE deal_id=$1",[data.deal_id])).rows[0].version);const total=data.items.reduce((sum,item)=>sum+item.quantity*item.unit_price,0);const token=randomBytes(32).toString("hex");const proposal=(await run("INSERT INTO sales_proposals(workspace_id,deal_id,version,valid_until,notes,total,public_token_hash,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING id",[workspace.id,data.deal_id,version,data.valid_until??null,data.notes,total,hash(token),user.id])).rows[0];for(const item of data.items)await run("INSERT INTO sales_proposal_items(proposal_id,product_id,description,quantity,unit_price) VALUES($1,$2,$3,$4,$5)",[proposal.id,item.product_id??null,item.description,item.quantity,item.unit_price]);return {id:proposal.id,version,total,publicToken:token};});return NextResponse.json(result,{status:201});}catch(error){return operationError(error);}}
export async function PATCH(request:Request){try{const {workspace}=await workspaceAccess();const data=z.object({id:uuid,status:z.enum(["draft","sent","accepted","declined","expired"])}).parse(await readJson(request,4096));const result=await adminQuery("UPDATE sales_proposals SET status=$1,sent_at=CASE WHEN $1='sent' THEN coalesce(sent_at,now()) ELSE sent_at END,accepted_at=CASE WHEN $1='accepted' THEN coalesce(accepted_at,now()) ELSE accepted_at END WHERE id=$2 AND workspace_id=$3 RETURNING id",[data.status,data.id,workspace.id]);if(!result.rowCount)throw new InputError("Proposta não encontrada.");return NextResponse.json({ok:true});}catch(error){return operationError(error);}}
