"use client";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
type Deal = { id: string; title: string; value?: number | null };
type Proposal = { id: string; deal_id: string; version: number; status: string; total: number; valid_until?: string | null; deals?: { title?: string } | null };
export function ProposalPanel({ deals, proposals }: { deals: Deal[]; proposals: Proposal[] }) {
  const [dealId, setDealId] = useState(deals[0]?.id ?? ""); const [description, setDescription] = useState("Serviço / produto"); const [quantity, setQuantity] = useState("1"); const [price, setPrice] = useState(""); const [notes, setNotes] = useState(""); const [validUntil, setValidUntil] = useState(""); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  async function createProposal() { setBusy(true); setMessage(""); try { const response = await fetch("/api/proposals", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ deal_id: dealId, valid_until: validUntil || null, notes, items: [{ description, quantity: Number(quantity), unit_price: Number(price) }] }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || "Não foi possível criar."); setMessage(`Proposta v${data.version} criada. Token público: ${data.publicToken}`); } catch (error) { setMessage(error instanceof Error ? error.message : "Erro inesperado."); } finally { setBusy(false); } }
  return <main className="mx-auto max-w-5xl space-y-6 p-6"><div><h1 className="text-2xl font-semibold">Propostas comerciais</h1><p className="text-sm text-muted-foreground">Crie versões, envie um link público e acompanhe aceite.</p></div><section className="rounded-xl border bg-card p-5 shadow-sm"><h2 className="font-medium">Nova proposta</h2><div className="mt-4 grid gap-3 md:grid-cols-2"><label className="text-sm">Negócio<select className="mt-1 flex h-10 w-full rounded-md border bg-background px-3" value={dealId} onChange={e => setDealId(e.target.value)}>{deals.map(deal => <option key={deal.id} value={deal.id}>{deal.title}</option>)}</select></label><label className="text-sm">Validade<input className="mt-1 flex h-10 w-full rounded-md border bg-background px-3" type="date" value={validUntil} onChange={e => setValidUntil(e.target.value)} /></label><label className="text-sm">Descrição<Input value={description} onChange={e => setDescription(e.target.value)} /></label><label className="text-sm">Preço unitário<Input type="number" min="0" value={price} onChange={e => setPrice(e.target.value)} /></label><label className="text-sm">Quantidade<Input type="number" min="1" value={quantity} onChange={e => setQuantity(e.target.value)} /></label><label className="text-sm md:col-span-2">Observações<Textarea value={notes} onChange={e => setNotes(e.target.value)} /></label></div><Button className="mt-4" disabled={busy || !dealId || !price} onClick={createProposal}>{busy ? "Criando…" : "Criar proposta"}</Button>{message && <p className="mt-3 break-all text-sm text-muted-foreground">{message}</p>}</section><section className="rounded-xl border bg-card p-5 shadow-sm"><h2 className="font-medium">Histórico</h2><div className="mt-3 divide-y">{proposals.map(proposal => <div key={proposal.id} className="flex items-center justify-between gap-4 py-3 text-sm"><span>{proposal.deals?.title ?? "Negócio"} · v{proposal.version}</span><span className="text-muted-foreground">{proposal.status} · R$ {Number(proposal.total).toLocaleString("pt-BR", { minimumFractionDigits: 2 })}</span></div>)}{proposals.length === 0 && <p className="py-4 text-sm text-muted-foreground">Nenhuma proposta criada.</p>}</div></section></main>;
}
