import { NextResponse } from "next/server";
import { z } from "zod";
import { workspaceAccess } from "@/lib/access";
import { adminQuery } from "@/lib/db/pool";
import { readJson, uuid } from "@/lib/security";
import { operationError } from "@/lib/operations-api";
const input = z.object({ name: z.string().trim().min(2).max(80), key: z.string().trim().regex(/^[a-z][a-z0-9_]+$/).max(40), stages: z.array(z.object({ key: z.string().regex(/^[a-z][a-z0-9_]+$/), title: z.string().trim().min(1).max(80), is_won: z.boolean().default(false), is_lost: z.boolean().default(false) })).min(2).max(30) });
export async function GET() { try { const { workspace } = await workspaceAccess(); const result = await adminQuery("SELECT p.id,p.name,p.pipeline_key,p.active,coalesce(json_agg(s ORDER BY s.position) FILTER (WHERE s.id IS NOT NULL),'[]') AS stages FROM sales_pipelines p LEFT JOIN sales_pipeline_stages s ON s.pipeline_id=p.id WHERE p.workspace_id=$1 GROUP BY p.id ORDER BY p.name", [workspace.id]); return NextResponse.json(result.rows); } catch (error) { return operationError(error); } }
export async function POST(request: Request) { try { const { workspace } = await workspaceAccess(true); const data = input.parse(await readJson(request, 20000)); const result = await adminQuery("INSERT INTO sales_pipelines(workspace_id,name,pipeline_key) VALUES($1,$2,$3) RETURNING id", [workspace.id, data.name, data.key]); const id = result.rows[0].id; for (const [position, stage] of data.stages.entries()) await adminQuery("INSERT INTO sales_pipeline_stages(pipeline_id,stage_key,title,position,is_won,is_lost) VALUES($1,$2,$3,$4,$5,$6)", [id, stage.key, stage.title, position, stage.is_won, stage.is_lost]); return NextResponse.json({ id }, { status: 201 }); } catch (error) { return operationError(error); } }
export async function PATCH(request: Request) { try { const { workspace } = await workspaceAccess(true); const data = z.object({ id: uuid, active: z.boolean().optional(), name: z.string().trim().min(2).max(80).optional() }).parse(await readJson(request, 4000)); await adminQuery("UPDATE sales_pipelines SET active=coalesce($1,active),name=coalesce($2,name) WHERE id=$3 AND workspace_id=$4", [data.active ?? null, data.name ?? null, data.id, workspace.id]); return NextResponse.json({ ok: true }); } catch (error) { return operationError(error); } }
