"use client";
import {useEffect,useState} from "react";
import Link from "next/link";
import {Button} from "@/components/ui/button";
import {Input} from "@/components/ui/input";
import {Dialog,DialogContent,DialogHeader,DialogTitle} from "@/components/ui/dialog";
import {defaultFilters,entityLabels,type SearchFilters,type SearchResult} from "@/lib/crm-search";
type View={id:string;name:string;filters:SearchFilters};
const fieldLabels:Record<string,string>={full_name:"Nome",title:"Título",name:"Nome",email:"E-mail",phone:"Telefone",company:"Empresa",organization_name:"Empresa",owner_name:"Responsável",assignee_name:"Responsável",value:"Valor",content:"Conteúdo",due_at:"Prazo",stage:"Etapa",status:"Status",outcome:"Resultado",custom_data:"Campos personalizados"};
export function SearchPanel({initial}:{initial:SearchFilters}){
 const [draft,setDraft]=useState(initial),[applied,setApplied]=useState(initial),[rows,setRows]=useState<SearchResult[]>([]),[next,setNext]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(""),[views,setViews]=useState<View[]>([]),[name,setName]=useState(""),[selected,setSelected]=useState<SearchResult|null>(null),[saving,setSaving]=useState(false);
 useEffect(()=>{const controller=new AbortController();const params=new URLSearchParams(Object.entries(applied).map(([k,v])=>[k,String(v)]));fetch("/api/crm/search?"+params,{signal:controller.signal}).then(async r=>{const data=await r.json();if(!r.ok)throw Error(data.error);return data;}).then(data=>{setRows(data.rows);setNext(data.hasNext);setError("");}).catch(e=>{if(e.name!=="AbortError")setError(e.message);}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});return()=>controller.abort();},[applied]);
 useEffect(()=>{let live=true;fetch("/api/crm/views").then(async r=>{if(!r.ok)throw Error("Falha ao carregar filtros salvos.");return r.json();}).then(data=>{if(live)setViews(data);}).catch(e=>{if(live)setError(e.message);});return()=>{live=false;};},[]);
 function search(value:SearchFilters){setLoading(true);setSelected(null);setApplied({...value});setDraft(value);window.history.replaceState(null,"","?"+new URLSearchParams(Object.entries(value).map(([k,v])=>[k,String(v)])));}
 async function updateView(body:unknown){setSaving(true);try{const r=await fetch("/api/crm/views",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const data=await r.json();if(!r.ok)throw Error(data.error);const response=await fetch("/api/crm/views");if(!response.ok)throw Error("Falha ao atualizar filtros.");setViews(await response.json());setName("");}catch(e){setError(e instanceof Error?e.message:"Falha.");}finally{setSaving(false);}}
 return <section className="space-y-5"><header><h1 className="text-2xl font-semibold">Busca global</h1><p className="text-sm text-muted-foreground">Pesquise os registros de toda a empresa e salve suas consultas.</p></header><form className="space-y-3 rounded-xl border bg-white p-4" onSubmit={e=>{e.preventDefault();search({...draft,page:1});}}><div className="flex flex-wrap gap-2"><Input aria-label="Buscar em todos os registros" className="min-w-48 flex-1" placeholder="Nome, e-mail, telefone ou conteúdo…" value={draft.q} onChange={e=>setDraft({...draft,q:e.target.value})}/><Button disabled={loading}>Buscar</Button><Button type="button" variant="outline" onClick={()=>search(defaultFilters)}>Limpar</Button></div><div className="grid gap-3 sm:grid-cols-3 lg:grid-cols-6"><label className="text-sm">Módulo<select className="mt-1 block w-full rounded border p-2" value={draft.entity} onChange={e=>setDraft({...draft,entity:e.target.value as SearchFilters["entity"]})}>{Object.entries(entityLabels).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label className="text-sm">Registros<select className="mt-1 block w-full rounded border p-2" value={draft.active} onChange={e=>setDraft({...draft,active:e.target.value as SearchFilters["active"]})}><option value="true">Ativos</option><option value="false">Arquivados</option><option value="all">Todos</option></select></label><label className="text-sm">Responsável (nome exato)<Input value={draft.owner} onChange={e=>setDraft({...draft,owner:e.target.value})}/></label><label className="text-sm">Etapa / status (identificador)<Input value={draft.status} onChange={e=>setDraft({...draft,status:e.target.value})}/></label><label className="text-sm">Sem atualização<select className="mt-1 block w-full rounded border p-2" value={draft.stale} onChange={e=>setDraft({...draft,stale:e.target.value as SearchFilters["stale"]})}><option value="0">Qualquer</option>{[7,14,30].map(n=><option key={n} value={n}>Há {n} dias</option>)}</select></label><label className="text-sm">Prazo de tarefas<select className="mt-1 block w-full rounded border p-2" value={draft.due} onChange={e=>setDraft({...draft,due:e.target.value as SearchFilters["due"]})}><option value="any">Qualquer</option><option value="overdue">Vencido</option><option value="today">Hoje</option></select></label></div><p className="text-xs text-muted-foreground">Os filtros são combinados. Prazo se aplica a tarefas; sem atualização considera a última edição do registro.</p></form>
 <div className="flex flex-wrap items-center gap-2"><Input className="max-w-xs" aria-label="Nome do filtro" placeholder="Nome para salvar os filtros aplicados" maxLength={80} value={name} onChange={e=>setName(e.target.value)}/><Button variant="outline" disabled={!name.trim()||saving} onClick={()=>updateView({action:"save",name,filters:applied})}>Salvar filtro aplicado</Button>{views.map(v=><div key={v.id} className="flex rounded border bg-white"><Button variant="ghost" onClick={()=>search(v.filters)}>{v.name}</Button><Button variant="ghost" disabled={saving} aria-label={"Excluir filtro "+v.name} onClick={()=>updateView({action:"delete",id:v.id})}>×</Button></div>)}</div>
 {error && <p role="alert" className="text-destructive">{error}</p>}{loading?<p role="status">Buscando…</p>:rows.length===0?<p className="rounded border bg-white p-8">Nenhum registro encontrado. Ajuste os filtros.</p>:<div className="overflow-auto rounded-xl border bg-white"><table className="w-full text-left text-sm"><thead><tr><th className="p-3">Registro</th><th>Módulo</th><th>Responsável</th><th>Status</th><th>Atualizado</th></tr></thead><tbody>{rows.map(row=><tr key={row.entity+row.id} className="border-t"><td className="p-3"><button className="text-left font-medium text-violet-700 underline-offset-4 hover:underline" onClick={()=>setSelected(row)}>{row.title}</button><p className="text-xs text-muted-foreground">{row.email||row.phone}</p></td><td>{entityLabels[row.entity]}</td><td>{row.owner||"—"}</td><td>{row.status||"—"}</td><td>{new Date(row.updated_at).toLocaleDateString("pt-BR")}</td></tr>)}</tbody></table></div>}
 <div className="flex items-center gap-3"><Button variant="outline" disabled={loading||applied.page===1} onClick={()=>search({...applied,page:applied.page-1})}>Anterior</Button><span>Página {applied.page}</span><Button variant="outline" disabled={loading||!next} onClick={()=>search({...applied,page:applied.page+1})}>Próxima</Button></div>
 <Dialog open={Boolean(selected)} onOpenChange={open=>{if(!open)setSelected(null);}}><DialogContent className="max-h-[85vh] overflow-auto"><DialogHeader><DialogTitle>{selected?.title}</DialogTitle></DialogHeader>{selected && <><dl className="space-y-3">{Object.entries(selected.detail).filter(([key,value])=>fieldLabels[key] && value!=null).map(([key,value])=><div key={key}><dt className="text-xs text-muted-foreground">{fieldLabels[key]}</dt><dd className="whitespace-pre-wrap break-words text-sm">{typeof value==="object"?JSON.stringify(value,null,2):String(value)}</dd></div>)}</dl><Link className="text-violet-700 underline" href={"/app/"+selected.entity}>Abrir módulo de {entityLabels[selected.entity].toLowerCase()}</Link></>}</DialogContent></Dialog>
 </section>;
}
