"use client";
import {useEffect,useState} from "react";
import {Button} from "@/components/ui/button";
import {Input} from "@/components/ui/input";
type Connection={phone_number_id:string;display_phone:string;enabled:boolean;updated_at:string}|null;
type Conversation={id:string;wa_id:string;name:string;updated_at:string;messages:{id:string;direction:"in"|"out";body:string;status:string;created_at:string}[]|null};
export function WhatsAppPanel(){const [connection,setConnection]=useState<Connection>(null),[phone,setPhone]=useState(""),[display,setDisplay]=useState(""),[token,setToken]=useState(""),[conversations,setConversations]=useState<Conversation[]>([]),[selected,setSelected]=useState<Conversation|null>(null),[body,setBody]=useState(""),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
 async function load(){const [a,b]=await Promise.all([fetch("/api/whatsapp/connection"),fetch("/api/whatsapp/conversations")]);if(a.ok)setConnection(await a.json());if(b.ok)setConversations(await b.json());}
 useEffect(()=>{void load().catch(e=>setMessage(e.message));},[]);
 async function save(){setBusy(true);try{const r=await fetch("/api/whatsapp/connection",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({phoneNumberId:phone,displayPhone:display,accessToken:token})});const d=await r.json();if(!r.ok)throw Error(d.error);setToken("");setMessage("WhatsApp conectado. A Meta precisa validar o webhook antes de enviar eventos.");await load();}catch(e){setMessage(e instanceof Error?e.message:"Falha.");}finally{setBusy(false);}}
 async function send(){if(!selected||!body.trim())return;setBusy(true);try{const r=await fetch("/api/whatsapp/messages",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({conversationId:selected.id,body})});const d=await r.json();if(!r.ok)throw Error(d.error);setBody("");setMessage("Mensagem enviada.");await load();}catch(e){setMessage(e instanceof Error?e.message:"Falha ao enviar.");}finally{setBusy(false);}}
 return <section className="space-y-6"><header><h2 className="text-xl font-semibold">WhatsApp Business</h2><p className="text-sm text-muted-foreground">Conecte a WhatsApp Cloud API oficial. A chave fica criptografada e nunca é mostrada novamente.</p></header><div className="grid gap-6 lg:grid-cols-[minmax(0,380px)_1fr]"><form className="space-y-4 rounded-xl border bg-white p-5" onSubmit={e=>{e.preventDefault();void save();}}><h3 className="font-semibold">Conexão</h3><label className="text-sm">Phone Number ID<Input required pattern="\d{6,30}" value={phone||connection?.phone_number_id||""} onChange={e=>setPhone(e.target.value)} /></label><label className="text-sm">Número exibido<Input required value={display||connection?.display_phone||""} onChange={e=>setDisplay(e.target.value)} /></label><label className="text-sm">Token permanente<Input required minLength={20} type="password" autoComplete="new-password" value={token} onChange={e=>setToken(e.target.value)} placeholder="Cole um novo token para atualizar" /></label><p className="text-xs text-muted-foreground">Configure WHATSAPP_APP_SECRET e WHATSAPP_VERIFY_TOKEN no servidor e cadastre este endereço no painel da Meta: <code>/api/whatsapp/webhook</code>.</p><Button disabled={busy}>Salvar conexão</Button>{connection&&<p className="text-xs">Atualizada em {new Date(connection.updated_at).toLocaleString("pt-BR")}</p>}</form><div className="rounded-xl border bg-white p-5"><h3 className="mb-3 font-semibold">Conversas recebidas</h3>{conversations.length===0?<p className="text-sm text-muted-foreground">Nenhuma conversa ainda. Após a validação do webhook, as mensagens aparecerão aqui.</p>:<div className="grid gap-2">{conversations.map(c=><button key={c.id} className="rounded border p-3 text-left hover:bg-muted" onClick={()=>setSelected(c)}><strong>{c.name}</strong><span className="ml-2 text-xs text-muted-foreground">{c.wa_id}</span><p className="truncate text-sm text-muted-foreground">{c.messages?.[0]?.body??"Sem mensagens"}</p></button>)}</div>}{selected&&<div className="mt-5 border-t pt-4"><h4 className="font-medium">{selected.name}</h4><div className="max-h-64 space-y-2 overflow-auto py-3">{selected.messages?.slice().reverse().map(m=><p key={m.id} className={m.direction==="out"?"ml-8 rounded bg-violet-100 p-2 text-sm":"mr-8 rounded bg-muted p-2 text-sm"}>{m.body}</p>)}</div><div className="flex gap-2"><Input aria-label="Mensagem WhatsApp" value={body} onChange={e=>setBody(e.target.value)} maxLength={4096} placeholder="Digite uma mensagem"/><Button disabled={busy||!body.trim()} onClick={()=>void send()}>Enviar</Button></div></div>}</div></div>{message&&<p role="status" className="rounded bg-muted p-3 text-sm">{message}</p>}</section>}
