"use client";
import {useEffect,useState} from "react";
import {Button} from "@/components/ui/button";
import {Input} from "@/components/ui/input";
type Data={rules:{id:string;name:string;trigger:string;enabled:boolean}[];runs:{id:string;name:string;state:string;attempts:number;error:string|null}[];members:{id:string;full_name:string}[];stages:{id:string;title:string}[];heartbeat:string|null};
const templates={lead_created:{name:"Primeiro contato",title:"Entrar em contato com o lead",delay_hours:1,action:"task"},deal_stage:{name:"Retorno da proposta",title:"Acompanhar proposta",delay_hours:24,action:"task"},deal_stale:{name:"Negócio parado",title:"Revisar negócio sem atualização",delay_hours:168,action:"notification"}};
export function AutomationsPanel(){
 const [data,setData]=useState<Data|null>(null),[message,setMessage]=useState(""),[busy,setBusy]=useState(false),[trigger,setTrigger]=useState<keyof typeof templates>("lead_created"),[name,setName]=useState(templates.lead_created.name),[title,setTitle]=useState(templates.lead_created.title),[hours,setHours]=useState(1),[action,setAction]=useState("task"),[stage,setStage]=useState(""),[assignee,setAssignee]=useState("");
 useEffect(()=>{let live=true;fetch("/api/crm/automations").then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.error);return d;}).then(d=>{if(live)setData(d);}).catch(e=>{if(live)setMessage(e.message);});return()=>{live=false;};},[]);
 async function refresh(){const r=await fetch("/api/crm/automations");const d=await r.json();if(!r.ok)throw Error(d.error);setData(d);}
 async function mutate(body:unknown){setBusy(true);setMessage("");try{const r=await fetch("/api/crm/automations",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw Error(d.error);await refresh();setMessage("Configuração atualizada.");}catch(e){setMessage(e instanceof Error?e.message:"Falha.");}finally{setBusy(false);}}
 return <section className="space-y-5"><div className="flex items-center justify-between"><div><h2 className="text-xl font-semibold">Automações comerciais</h2><p className="text-sm text-muted-foreground">Crie acompanhamentos e alertas sem repetir tarefas manualmente.</p></div><Button variant="outline" onClick={()=>refresh().catch(e=>setMessage(e.message))}>Atualizar</Button></div>
 {data && <p role="status" className="rounded border bg-white p-3 text-sm">{data.heartbeat && Date.now()-Date.parse(data.heartbeat)<120000?"Processador ativo. As regras são verificadas periodicamente.":"Processador sem sinal recente. As regras serão executadas quando o serviço de automações estiver ativo."}</p>}
 <form className="grid gap-4 rounded-xl border bg-white p-5 sm:grid-cols-2" onSubmit={e=>{e.preventDefault();void mutate({action:"create",rule:{name,trigger,title,delay_hours:hours,stage,action,assignee_id:assignee||null}});}}><label className="text-sm">Quando<select className="mt-1 block w-full rounded border p-2" value={trigger} onChange={e=>{const key=e.target.value as keyof typeof templates;setTrigger(key);setName(templates[key].name);setTitle(templates[key].title);setHours(templates[key].delay_hours);setAction(templates[key].action);}}><option value="lead_created">Um lead for criado</option><option value="deal_stage">Negócio entrar em uma etapa</option><option value="deal_stale">Negócio ficar sem atualização</option></select></label><label className="text-sm">Nome da regra<Input required maxLength={100} value={name} onChange={e=>setName(e.target.value)}/></label>{trigger==="deal_stage" && <label className="text-sm">Etapa<select required className="mt-1 block w-full rounded border p-2" value={stage} onChange={e=>setStage(e.target.value)}><option value="">Selecione</option>{data?.stages.map(s=><option key={s.id} value={s.id}>{s.title}</option>)}</select></label>}<label className="text-sm">{trigger==="deal_stale"?"Horas sem atualização":"Prazo da tarefa, em horas"}<Input type="number" required min={1} max={8760} value={hours} onChange={e=>setHours(Number(e.target.value))}/></label><label className="text-sm">Ação<select className="mt-1 block w-full rounded border p-2" value={action} onChange={e=>setAction(e.target.value)}><option value="task">Criar tarefa e notificar</option><option value="notification">Criar notificação</option></select></label><label className="text-sm">Título da tarefa / notificação<Input required maxLength={180} value={title} onChange={e=>setTitle(e.target.value)}/></label><label className="text-sm">Responsável<select className="mt-1 block w-full rounded border p-2" value={assignee} onChange={e=>setAssignee(e.target.value)}><option value="">Proprietário da empresa</option>{data?.members.map(m=><option key={m.id} value={m.id}>{m.full_name||"Membro"}</option>)}</select></label><p className="text-xs text-muted-foreground sm:col-span-2">Regras de criação e etapa consideram eventos posteriores à ativação inicial. Negócios parados consideram registros abertos existentes. Dados de demonstração não disparam regras. Nenhuma mensagem externa é enviada automaticamente.</p><Button disabled={busy||!data}>Ativar regra</Button></form>
 {message&&<p role="status">{message}</p>}<div className="space-y-2">{data?.rules.map(r=><div key={r.id} className="flex items-center justify-between rounded border bg-white p-4"><div><p className="font-medium">{r.name}</p><p className="text-sm text-muted-foreground">{r.enabled?"Ativa":"Pausada"}</p></div><Button variant="outline" disabled={busy} onClick={()=>mutate({action:"toggle",id:r.id,enabled:!r.enabled})}>{r.enabled?"Pausar":"Retomar"}</Button></div>)}</div><h3 className="font-semibold">Últimas 50 execuções</h3><div className="space-y-2">{data?.runs.length===0&&<p className="text-sm">Ainda não houve execuções.</p>}{data?.runs.map(r=><div key={r.id} className="rounded border bg-white p-3 text-sm"><strong>{r.name}</strong> · {({pending:"Aguardando",done:"Concluída",failed:"Falhou",skipped:"Ignorada"} as Record<string,string>)[r.state]} · {r.attempts} tentativa(s){r.error&&<p>{r.error}</p>}{r.state==="failed"&&<Button disabled={busy} variant="outline" onClick={()=>mutate({action:"retry",id:r.id})}>Tentar novamente</Button>}</div>)}</div></section>;
}
