import { workspaceAccess } from "@/lib/access";

export default async function ReportsPage() {
  const { db, workspace } = await workspaceAccess();
  const [{ data: deals }, { data: goals }, { data: leads }] = await Promise.all([
    db.from("deals").select("id,title,stage,value,loss_reason,owner_id,updated_at").eq("workspace_id", workspace.id).eq("active", true).limit(1000),
    db.from("sales_goals").select("period_start,period_end,target_revenue,target_wins").eq("workspace_id", workspace.id).order("period_start", { ascending: false }).limit(1),
    db.from("leads").select("id,custom_data").eq("workspace_id", workspace.id).eq("active", true).limit(1000),
  ]);
  const rows = deals ?? []; const won = rows.filter(row => row.stage === "won"); const lost = rows.filter(row => row.stage === "lost"); const pipeline = rows.filter(row => row.stage !== "won" && row.stage !== "lost"); const revenue = won.reduce((sum, row) => sum + Number(row.value ?? 0), 0); const goal = goals?.[0];
  const sources = new Map<string, number>(); for (const lead of leads ?? []) { const source = typeof lead.custom_data?.source === "string" && lead.custom_data.source.trim() ? lead.custom_data.source : "Sem origem"; sources.set(source, (sources.get(source) ?? 0) + 1); }
  return <main className="mx-auto max-w-6xl space-y-6 p-6"><div><h1 className="text-2xl font-semibold">Relatórios comerciais</h1><p className="text-sm text-muted-foreground">Visão operacional de funil, conversão, receita e origem.</p></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[["Negócios ativos", rows.length], ["Em aberto", pipeline.length], ["Ganhos", won.length], ["Receita ganha", `R$ ${revenue.toLocaleString("pt-BR", { minimumFractionDigits: 2 })}`]].map(([label, value]) => <div className="rounded-xl border bg-card p-5 shadow-sm" key={String(label)}><p className="text-sm text-muted-foreground">{label}</p><p className="mt-2 text-2xl font-semibold">{value}</p></div>)}</div><div className="grid gap-6 lg:grid-cols-2"><section className="rounded-xl border bg-card p-5 shadow-sm"><h2 className="font-medium">Meta atual</h2><p className="mt-3 text-sm text-muted-foreground">{goal ? `${goal.period_start} a ${goal.period_end}` : "Nenhuma meta cadastrada"}</p><p className="mt-2 text-2xl font-semibold">R$ {revenue.toLocaleString("pt-BR", { minimumFractionDigits: 2 })} <span className="text-sm font-normal text-muted-foreground">/ R$ {Number(goal?.target_revenue ?? 0).toLocaleString("pt-BR", { minimumFractionDigits: 2 })}</span></p><p className="mt-2 text-sm">{won.length} ganhos de {Number(goal?.target_wins ?? 0)} previstos</p></section><section className="rounded-xl border bg-card p-5 shadow-sm"><h2 className="font-medium">Conversão e perdas</h2><p className="mt-3 text-sm">Conversão do histórico ativo: <strong>{rows.length ? Math.round((won.length / rows.length) * 100) : 0}%</strong></p><p className="mt-2 text-sm text-muted-foreground">{lost.length} negócios perdidos. Registre o motivo na ficha para melhorar este diagnóstico.</p></section></div><section className="rounded-xl border bg-card p-5 shadow-sm"><h2 className="font-medium">Origem dos leads</h2><div className="mt-3 grid gap-2 sm:grid-cols-2 lg:grid-cols-4">{Array.from(sources.entries()).sort((a,b) => b[1]-a[1]).map(([source, count]) => <div className="rounded-lg bg-muted/40 p-3 text-sm" key={source}><span>{source}</span><strong className="float-right">{count}</strong></div>)}{sources.size === 0 && <p className="text-sm text-muted-foreground">Sem dados de origem.</p>}</div></section></main>;
}
